url: https://austeresurgical.com
baseurl: /

# Site settings
title: Austere Surgical
email: info@austeresurgical.com
description: "Austere Surgical is pushing the boundary of surgical care in low-resource environments to improve patient outcomes in war zones, natural disasters, and spaceflight. Our portable and reusable system provides stability, sterility, and visibility in remote environments. From offloading minor procedures in overrun hospitals to providing damage control surgery on the move, our system deploys a functional operating room when you need it most."


# Team names, titles and social links
people:
- name: Neil Koby Reid, MS
  pic: Reid
  position: Interim CEO, Incoming Surgery Resident @ BUMC Dallas
  group: cofounder
  social:
    - title: linkedin
      url: www.linkedin.com/in/nkreid

- name: Jacob Paris
  pic: Paris
  position: Incoming Medicine Resident @ Kansas
  group: cofounder
  social:
    - title: linkedin
      url: #

- name: Brayden Raper
  pic: Raper
  position: Incoming Anesthesia Resident @ Vanderbilt
  group: cofounder
  social:
    - title: linkedin
      url: #

  - name: Drew Hendricks, MBE
  pic: Hendricks
  position: Incoming Emergency Medicine Resident @ Stanford
  group: cofounder
  social:
    - title: linkedin
      url: #

  - name: Rebecca Lee, MD
  pic: Lee
  position: Clinical & University Relations
  group: advisor
  social:
    - title: linkedin
      url: #

  - name: Walter Cromer, PhD
  pic: Cromer
  position: Microbiology & Sanitization
  group: advisor
  social:
    - title: linkedin
      url: #

  - name: Nick Sears, PhD
  pic: Sears
  position: Technical Engineering & Manufacturing
  group: advisor
  social:
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: github
    url: http://github.com/austeresurgical

# Postal address (add as many lines as necessary)
address:
  - line: 1020 Holcombe Blvd
  - line: Houston, TX 77030

# Build settings
markdown: kramdown
permalink: pretty
