url: https://austeresurgical.com
baseurl: /

# Site settings
title: Austere Surgical
email: info@austeresurgical.com
description: "Austere Surgical is pushing the boundary of surgical care in low-resource environments to improve patient outcomes in war zones, natural disasters, and spaceflight. Our portable and reusable system provides stability, sterility, and visibility in remote environments. From offloading minor procedures in overrun hospitals to providing damage control surgery on the move, our system deploys a functional operating room when you need it most."


# Team names, titles and social links
people:
- name: Neil Koby Reid, MS
  pic: Reid
  position: Interim CEO, Incoming Surgery Resident @ BUMC Dallas
  social:
    - title: linkedin
      url: www.linkedin.com/in/nkreid



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: github
    url: http://github.com/austeresurgical

# Postal address (add as many lines as necessary)
address:
  - line: 1020 Holcombe Blvd
  - line: Houston, TX 77030

# Build settings
markdown: kramdown
permalink: pretty
